<div>
    <a href="?action=test" class="btn btn-primary">&gt; Test</a>
</div>
<table>
    <tr>
        <th>&nbsp;</th>
        <th>Name</th>
        <th>Alter</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Willy</td>
        <td>23</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Achim</td>
        <td>25</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Sebastian</td>
        <td>22</td>
    </tr>
</table>
<p>Yunus Emrah Tuncer war hier</p>